name1 = input ("Enter your name: ")
print ("Your name is " + (name1))
print ("I can estimate your next 12 years")
age1 = int (input ("Enter your age: "))
print ("Your age will be " + str(age1 + 12))
idnum = input ("Enter your ID number: ")
print ("Your ID number is " + (idnum))
name2 = input ("Enter your Father's name: ")
print ("Your father's name is" + (name2))
name3 = input ("Enter your Mother's name: ")
print ("Your Mother's name is" + (name3))
name4 = input ("Enter your friend's name: ")
print ("Your friend's name is" + (name4)
name = input ("Enter your name: ")
print ("Your name is " + (name))
age = input ("Enter your age: ")
print ("Your age is " + (age))
number = input ("Enter your ID number: ")
print ("Your ID number is " + (number))
fbnum = input ("Enter your FB number: ")
print ("Your FB number is " + (fbnum))
DOB = ("Enter your DOB: ")
print = ("Your DOB is " + (DOB))
print ("Are you female or Male ")
FOM = input ("Enter your gender: ")
print = ("Your gender is " + (FOM))
hight = input ("Enter your hight: ")
print ("Your high is " + (hight))
print ("Your name is " + input ("enter your name: "))