num1 = int(input ("Enter your first number: "))
num2 = int(input ("Enter your second number: "))
print (num1 + num2)
num1 = int(input ("Enter your first number: "))
num2 = int(input ("Enter your second number: "))
print (num1 - num2)
num1 = int(input ("Enter your first number: "))
num2 = int(input ("Enter your second number: "))
print (num1 * num2)
num1 = int(input ("Enter your first number: "))
num2 = int(input ("Enter your second number: "))
num3 = int(input ("Enter your third number: "))
num4 = int(input ("Enter your fourth number: "))
num5 = int(input ("Enter your fifth number: "))
num6 = int(input ("Enter your sixth number: "))
print (num1 * num2 - num3 + num4 / num5 * num6)
num1 = int (input ("Enter your first number: "))
num2 = int (input ("Enter your second number: "))
num3 = int (input ("Enter your third number: "))
print (num1 * num2 + (num3 / num1) + num2)